/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVzasWeeksRouteImport } from './routes/api/vzas-weeks'
import { Route as ApiVzasStatusRouteImport } from './routes/api/vzas-status'
import { Route as ApiVzasSettingsRouteImport } from './routes/api/vzas-settings'
import { Route as ApiVzasNotesRouteImport } from './routes/api/vzas-notes'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiResetRouteImport } from './routes/api/reset'
import { Route as ApiOverrideRouteImport } from './routes/api/override'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiJarvisMemoryRouteImport } from './routes/api/jarvis-memory'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiDataRouteImport } from './routes/api/data'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiBtcReserveRouteImport } from './routes/api/btc-reserve'
import { Route as ApiAnomalyRouteImport } from './routes/api/anomaly'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVzasWeeksRoute = ApiVzasWeeksRouteImport.update({
  id: '/api/vzas-weeks',
  path: '/api/vzas-weeks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVzasStatusRoute = ApiVzasStatusRouteImport.update({
  id: '/api/vzas-status',
  path: '/api/vzas-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVzasSettingsRoute = ApiVzasSettingsRouteImport.update({
  id: '/api/vzas-settings',
  path: '/api/vzas-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVzasNotesRoute = ApiVzasNotesRouteImport.update({
  id: '/api/vzas-notes',
  path: '/api/vzas-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetRoute = ApiResetRouteImport.update({
  id: '/api/reset',
  path: '/api/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverrideRoute = ApiOverrideRouteImport.update({
  id: '/api/override',
  path: '/api/override',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJarvisMemoryRoute = ApiJarvisMemoryRouteImport.update({
  id: '/api/jarvis-memory',
  path: '/api/jarvis-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBtcReserveRoute = ApiBtcReserveRouteImport.update({
  id: '/api/btc-reserve',
  path: '/api/btc-reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnomalyRoute = ApiAnomalyRouteImport.update({
  id: '/api/anomaly',
  path: '/api/anomaly',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/anomaly': typeof ApiAnomalyRoute
  '/api/btc-reserve': typeof ApiBtcReserveRoute
  '/api/chat': typeof ApiChatRoute
  '/api/data': typeof ApiDataRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/jarvis-memory': typeof ApiJarvisMemoryRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/override': typeof ApiOverrideRoute
  '/api/reset': typeof ApiResetRoute
  '/api/session': typeof ApiSessionRoute
  '/api/vzas-notes': typeof ApiVzasNotesRoute
  '/api/vzas-settings': typeof ApiVzasSettingsRoute
  '/api/vzas-status': typeof ApiVzasStatusRoute
  '/api/vzas-weeks': typeof ApiVzasWeeksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/anomaly': typeof ApiAnomalyRoute
  '/api/btc-reserve': typeof ApiBtcReserveRoute
  '/api/chat': typeof ApiChatRoute
  '/api/data': typeof ApiDataRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/jarvis-memory': typeof ApiJarvisMemoryRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/override': typeof ApiOverrideRoute
  '/api/reset': typeof ApiResetRoute
  '/api/session': typeof ApiSessionRoute
  '/api/vzas-notes': typeof ApiVzasNotesRoute
  '/api/vzas-settings': typeof ApiVzasSettingsRoute
  '/api/vzas-status': typeof ApiVzasStatusRoute
  '/api/vzas-weeks': typeof ApiVzasWeeksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/anomaly': typeof ApiAnomalyRoute
  '/api/btc-reserve': typeof ApiBtcReserveRoute
  '/api/chat': typeof ApiChatRoute
  '/api/data': typeof ApiDataRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/jarvis-memory': typeof ApiJarvisMemoryRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/override': typeof ApiOverrideRoute
  '/api/reset': typeof ApiResetRoute
  '/api/session': typeof ApiSessionRoute
  '/api/vzas-notes': typeof ApiVzasNotesRoute
  '/api/vzas-settings': typeof ApiVzasSettingsRoute
  '/api/vzas-status': typeof ApiVzasStatusRoute
  '/api/vzas-weeks': typeof ApiVzasWeeksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/anomaly'
    | '/api/btc-reserve'
    | '/api/chat'
    | '/api/data'
    | '/api/ingest'
    | '/api/jarvis-memory'
    | '/api/leads'
    | '/api/login'
    | '/api/logout'
    | '/api/override'
    | '/api/reset'
    | '/api/session'
    | '/api/vzas-notes'
    | '/api/vzas-settings'
    | '/api/vzas-status'
    | '/api/vzas-weeks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/anomaly'
    | '/api/btc-reserve'
    | '/api/chat'
    | '/api/data'
    | '/api/ingest'
    | '/api/jarvis-memory'
    | '/api/leads'
    | '/api/login'
    | '/api/logout'
    | '/api/override'
    | '/api/reset'
    | '/api/session'
    | '/api/vzas-notes'
    | '/api/vzas-settings'
    | '/api/vzas-status'
    | '/api/vzas-weeks'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/anomaly'
    | '/api/btc-reserve'
    | '/api/chat'
    | '/api/data'
    | '/api/ingest'
    | '/api/jarvis-memory'
    | '/api/leads'
    | '/api/login'
    | '/api/logout'
    | '/api/override'
    | '/api/reset'
    | '/api/session'
    | '/api/vzas-notes'
    | '/api/vzas-settings'
    | '/api/vzas-status'
    | '/api/vzas-weeks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAnomalyRoute: typeof ApiAnomalyRoute
  ApiBtcReserveRoute: typeof ApiBtcReserveRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiJarvisMemoryRoute: typeof ApiJarvisMemoryRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiOverrideRoute: typeof ApiOverrideRoute
  ApiResetRoute: typeof ApiResetRoute
  ApiSessionRoute: typeof ApiSessionRoute
  ApiVzasNotesRoute: typeof ApiVzasNotesRoute
  ApiVzasSettingsRoute: typeof ApiVzasSettingsRoute
  ApiVzasStatusRoute: typeof ApiVzasStatusRoute
  ApiVzasWeeksRoute: typeof ApiVzasWeeksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vzas-weeks': {
      id: '/api/vzas-weeks'
      path: '/api/vzas-weeks'
      fullPath: '/api/vzas-weeks'
      preLoaderRoute: typeof ApiVzasWeeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vzas-status': {
      id: '/api/vzas-status'
      path: '/api/vzas-status'
      fullPath: '/api/vzas-status'
      preLoaderRoute: typeof ApiVzasStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vzas-settings': {
      id: '/api/vzas-settings'
      path: '/api/vzas-settings'
      fullPath: '/api/vzas-settings'
      preLoaderRoute: typeof ApiVzasSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vzas-notes': {
      id: '/api/vzas-notes'
      path: '/api/vzas-notes'
      fullPath: '/api/vzas-notes'
      preLoaderRoute: typeof ApiVzasNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset': {
      id: '/api/reset'
      path: '/api/reset'
      fullPath: '/api/reset'
      preLoaderRoute: typeof ApiResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/override': {
      id: '/api/override'
      path: '/api/override'
      fullPath: '/api/override'
      preLoaderRoute: typeof ApiOverrideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jarvis-memory': {
      id: '/api/jarvis-memory'
      path: '/api/jarvis-memory'
      fullPath: '/api/jarvis-memory'
      preLoaderRoute: typeof ApiJarvisMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/btc-reserve': {
      id: '/api/btc-reserve'
      path: '/api/btc-reserve'
      fullPath: '/api/btc-reserve'
      preLoaderRoute: typeof ApiBtcReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anomaly': {
      id: '/api/anomaly'
      path: '/api/anomaly'
      fullPath: '/api/anomaly'
      preLoaderRoute: typeof ApiAnomalyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAnomalyRoute: ApiAnomalyRoute,
  ApiBtcReserveRoute: ApiBtcReserveRoute,
  ApiChatRoute: ApiChatRoute,
  ApiDataRoute: ApiDataRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiJarvisMemoryRoute: ApiJarvisMemoryRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiOverrideRoute: ApiOverrideRoute,
  ApiResetRoute: ApiResetRoute,
  ApiSessionRoute: ApiSessionRoute,
  ApiVzasNotesRoute: ApiVzasNotesRoute,
  ApiVzasSettingsRoute: ApiVzasSettingsRoute,
  ApiVzasStatusRoute: ApiVzasStatusRoute,
  ApiVzasWeeksRoute: ApiVzasWeeksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
