/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiZositRouteImport } from './routes/api/zosit'
import { Route as ApiWishlistRouteImport } from './routes/api/wishlist'
import { Route as ApiWebObsahRouteImport } from './routes/api/web-obsah'
import { Route as ApiVzasWeeksRouteImport } from './routes/api/vzas-weeks'
import { Route as ApiVzasStatusRouteImport } from './routes/api/vzas-status'
import { Route as ApiVzasSettingsRouteImport } from './routes/api/vzas-settings'
import { Route as ApiVzasNotesRouteImport } from './routes/api/vzas-notes'
import { Route as ApiVedomostRouteImport } from './routes/api/vedomost'
import { Route as ApiUsersRouteImport } from './routes/api/users'
import { Route as ApiSsoRouteImport } from './routes/api/sso'
import { Route as ApiSpravaRouteImport } from './routes/api/sprava'
import { Route as ApiSessionRouteImport } from './routes/api/session'
import { Route as ApiResetRouteImport } from './routes/api/reset'
import { Route as ApiRawUploadsRouteImport } from './routes/api/raw-uploads'
import { Route as ApiPremenujRouteImport } from './routes/api/premenuj'
import { Route as ApiPlanyRouteImport } from './routes/api/plany'
import { Route as ApiPeriodsRouteImport } from './routes/api/periods'
import { Route as ApiPdfImportRouteImport } from './routes/api/pdf-import'
import { Route as ApiPagespeedRouteImport } from './routes/api/pagespeed'
import { Route as ApiOverrideRouteImport } from './routes/api/override'
import { Route as ApiNapadyRouteImport } from './routes/api/napady'
import { Route as ApiMetaMediaRouteImport } from './routes/api/meta-media'
import { Route as ApiMetaRouteImport } from './routes/api/meta'
import { Route as ApiMeraniaRouteImport } from './routes/api/merania'
import { Route as ApiMarketingRouteImport } from './routes/api/marketing'
import { Route as ApiMailerRouteImport } from './routes/api/mailer'
import { Route as ApiLogoutRouteImport } from './routes/api/logout'
import { Route as ApiLoginRouteImport } from './routes/api/login'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiLeadWebRouteImport } from './routes/api/lead-web'
import { Route as ApiKalendarRouteImport } from './routes/api/kalendar'
import { Route as ApiJarvisMemoryRouteImport } from './routes/api/jarvis-memory'
import { Route as ApiJarvisDokumentRouteImport } from './routes/api/jarvis-dokument'
import { Route as ApiIngestRouteImport } from './routes/api/ingest'
import { Route as ApiGoogleAdsRouteImport } from './routes/api/google-ads'
import { Route as ApiGoogleRouteImport } from './routes/api/google'
import { Route as ApiFioRouteImport } from './routes/api/fio'
import { Route as ApiFakturyRouteImport } from './routes/api/faktury'
import { Route as ApiExportRouteImport } from './routes/api/export'
import { Route as ApiDataRouteImport } from './routes/api/data'
import { Route as ApiClientNotesRouteImport } from './routes/api/client-notes'
import { Route as ApiClientDeleteRouteImport } from './routes/api/client-delete'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiBtcReserveRouteImport } from './routes/api/btc-reserve'
import { Route as ApiAnomalyRouteImport } from './routes/api/anomaly'
import { Route as ApiAlgoRouteImport } from './routes/api/algo'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZositRoute = ApiZositRouteImport.update({
  id: '/api/zosit',
  path: '/api/zosit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWishlistRoute = ApiWishlistRouteImport.update({
  id: '/api/wishlist',
  path: '/api/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebObsahRoute = ApiWebObsahRouteImport.update({
  id: '/api/web-obsah',
  path: '/api/web-obsah',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVzasWeeksRoute = ApiVzasWeeksRouteImport.update({
  id: '/api/vzas-weeks',
  path: '/api/vzas-weeks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVzasStatusRoute = ApiVzasStatusRouteImport.update({
  id: '/api/vzas-status',
  path: '/api/vzas-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVzasSettingsRoute = ApiVzasSettingsRouteImport.update({
  id: '/api/vzas-settings',
  path: '/api/vzas-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVzasNotesRoute = ApiVzasNotesRouteImport.update({
  id: '/api/vzas-notes',
  path: '/api/vzas-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVedomostRoute = ApiVedomostRouteImport.update({
  id: '/api/vedomost',
  path: '/api/vedomost',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersRoute = ApiUsersRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSsoRoute = ApiSsoRouteImport.update({
  id: '/api/sso',
  path: '/api/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpravaRoute = ApiSpravaRouteImport.update({
  id: '/api/sprava',
  path: '/api/sprava',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionRoute = ApiSessionRouteImport.update({
  id: '/api/session',
  path: '/api/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetRoute = ApiResetRouteImport.update({
  id: '/api/reset',
  path: '/api/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRawUploadsRoute = ApiRawUploadsRouteImport.update({
  id: '/api/raw-uploads',
  path: '/api/raw-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPremenujRoute = ApiPremenujRouteImport.update({
  id: '/api/premenuj',
  path: '/api/premenuj',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlanyRoute = ApiPlanyRouteImport.update({
  id: '/api/plany',
  path: '/api/plany',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPeriodsRoute = ApiPeriodsRouteImport.update({
  id: '/api/periods',
  path: '/api/periods',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPdfImportRoute = ApiPdfImportRouteImport.update({
  id: '/api/pdf-import',
  path: '/api/pdf-import',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPagespeedRoute = ApiPagespeedRouteImport.update({
  id: '/api/pagespeed',
  path: '/api/pagespeed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOverrideRoute = ApiOverrideRouteImport.update({
  id: '/api/override',
  path: '/api/override',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNapadyRoute = ApiNapadyRouteImport.update({
  id: '/api/napady',
  path: '/api/napady',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaMediaRoute = ApiMetaMediaRouteImport.update({
  id: '/api/meta-media',
  path: '/api/meta-media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaRoute = ApiMetaRouteImport.update({
  id: '/api/meta',
  path: '/api/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMeraniaRoute = ApiMeraniaRouteImport.update({
  id: '/api/merania',
  path: '/api/merania',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMarketingRoute = ApiMarketingRouteImport.update({
  id: '/api/marketing',
  path: '/api/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMailerRoute = ApiMailerRouteImport.update({
  id: '/api/mailer',
  path: '/api/mailer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLogoutRoute = ApiLogoutRouteImport.update({
  id: '/api/logout',
  path: '/api/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLoginRoute = ApiLoginRouteImport.update({
  id: '/api/login',
  path: '/api/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadWebRoute = ApiLeadWebRouteImport.update({
  id: '/api/lead-web',
  path: '/api/lead-web',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKalendarRoute = ApiKalendarRouteImport.update({
  id: '/api/kalendar',
  path: '/api/kalendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJarvisMemoryRoute = ApiJarvisMemoryRouteImport.update({
  id: '/api/jarvis-memory',
  path: '/api/jarvis-memory',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJarvisDokumentRoute = ApiJarvisDokumentRouteImport.update({
  id: '/api/jarvis-dokument',
  path: '/api/jarvis-dokument',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleAdsRoute = ApiGoogleAdsRouteImport.update({
  id: '/api/google-ads',
  path: '/api/google-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleRoute = ApiGoogleRouteImport.update({
  id: '/api/google',
  path: '/api/google',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFioRoute = ApiFioRouteImport.update({
  id: '/api/fio',
  path: '/api/fio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFakturyRoute = ApiFakturyRouteImport.update({
  id: '/api/faktury',
  path: '/api/faktury',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportRoute = ApiExportRouteImport.update({
  id: '/api/export',
  path: '/api/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientNotesRoute = ApiClientNotesRouteImport.update({
  id: '/api/client-notes',
  path: '/api/client-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClientDeleteRoute = ApiClientDeleteRouteImport.update({
  id: '/api/client-delete',
  path: '/api/client-delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBtcReserveRoute = ApiBtcReserveRouteImport.update({
  id: '/api/btc-reserve',
  path: '/api/btc-reserve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnomalyRoute = ApiAnomalyRouteImport.update({
  id: '/api/anomaly',
  path: '/api/anomaly',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlgoRoute = ApiAlgoRouteImport.update({
  id: '/api/algo',
  path: '/api/algo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/algo': typeof ApiAlgoRoute
  '/api/anomaly': typeof ApiAnomalyRoute
  '/api/btc-reserve': typeof ApiBtcReserveRoute
  '/api/chat': typeof ApiChatRoute
  '/api/client-delete': typeof ApiClientDeleteRoute
  '/api/client-notes': typeof ApiClientNotesRoute
  '/api/data': typeof ApiDataRoute
  '/api/export': typeof ApiExportRoute
  '/api/faktury': typeof ApiFakturyRoute
  '/api/fio': typeof ApiFioRoute
  '/api/google': typeof ApiGoogleRoute
  '/api/google-ads': typeof ApiGoogleAdsRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/jarvis-dokument': typeof ApiJarvisDokumentRoute
  '/api/jarvis-memory': typeof ApiJarvisMemoryRoute
  '/api/kalendar': typeof ApiKalendarRoute
  '/api/lead-web': typeof ApiLeadWebRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/mailer': typeof ApiMailerRoute
  '/api/marketing': typeof ApiMarketingRoute
  '/api/merania': typeof ApiMeraniaRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/meta-media': typeof ApiMetaMediaRoute
  '/api/napady': typeof ApiNapadyRoute
  '/api/override': typeof ApiOverrideRoute
  '/api/pagespeed': typeof ApiPagespeedRoute
  '/api/pdf-import': typeof ApiPdfImportRoute
  '/api/periods': typeof ApiPeriodsRoute
  '/api/plany': typeof ApiPlanyRoute
  '/api/premenuj': typeof ApiPremenujRoute
  '/api/raw-uploads': typeof ApiRawUploadsRoute
  '/api/reset': typeof ApiResetRoute
  '/api/session': typeof ApiSessionRoute
  '/api/sprava': typeof ApiSpravaRoute
  '/api/sso': typeof ApiSsoRoute
  '/api/users': typeof ApiUsersRoute
  '/api/vedomost': typeof ApiVedomostRoute
  '/api/vzas-notes': typeof ApiVzasNotesRoute
  '/api/vzas-settings': typeof ApiVzasSettingsRoute
  '/api/vzas-status': typeof ApiVzasStatusRoute
  '/api/vzas-weeks': typeof ApiVzasWeeksRoute
  '/api/web-obsah': typeof ApiWebObsahRoute
  '/api/wishlist': typeof ApiWishlistRoute
  '/api/zosit': typeof ApiZositRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/algo': typeof ApiAlgoRoute
  '/api/anomaly': typeof ApiAnomalyRoute
  '/api/btc-reserve': typeof ApiBtcReserveRoute
  '/api/chat': typeof ApiChatRoute
  '/api/client-delete': typeof ApiClientDeleteRoute
  '/api/client-notes': typeof ApiClientNotesRoute
  '/api/data': typeof ApiDataRoute
  '/api/export': typeof ApiExportRoute
  '/api/faktury': typeof ApiFakturyRoute
  '/api/fio': typeof ApiFioRoute
  '/api/google': typeof ApiGoogleRoute
  '/api/google-ads': typeof ApiGoogleAdsRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/jarvis-dokument': typeof ApiJarvisDokumentRoute
  '/api/jarvis-memory': typeof ApiJarvisMemoryRoute
  '/api/kalendar': typeof ApiKalendarRoute
  '/api/lead-web': typeof ApiLeadWebRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/mailer': typeof ApiMailerRoute
  '/api/marketing': typeof ApiMarketingRoute
  '/api/merania': typeof ApiMeraniaRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/meta-media': typeof ApiMetaMediaRoute
  '/api/napady': typeof ApiNapadyRoute
  '/api/override': typeof ApiOverrideRoute
  '/api/pagespeed': typeof ApiPagespeedRoute
  '/api/pdf-import': typeof ApiPdfImportRoute
  '/api/periods': typeof ApiPeriodsRoute
  '/api/plany': typeof ApiPlanyRoute
  '/api/premenuj': typeof ApiPremenujRoute
  '/api/raw-uploads': typeof ApiRawUploadsRoute
  '/api/reset': typeof ApiResetRoute
  '/api/session': typeof ApiSessionRoute
  '/api/sprava': typeof ApiSpravaRoute
  '/api/sso': typeof ApiSsoRoute
  '/api/users': typeof ApiUsersRoute
  '/api/vedomost': typeof ApiVedomostRoute
  '/api/vzas-notes': typeof ApiVzasNotesRoute
  '/api/vzas-settings': typeof ApiVzasSettingsRoute
  '/api/vzas-status': typeof ApiVzasStatusRoute
  '/api/vzas-weeks': typeof ApiVzasWeeksRoute
  '/api/web-obsah': typeof ApiWebObsahRoute
  '/api/wishlist': typeof ApiWishlistRoute
  '/api/zosit': typeof ApiZositRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/algo': typeof ApiAlgoRoute
  '/api/anomaly': typeof ApiAnomalyRoute
  '/api/btc-reserve': typeof ApiBtcReserveRoute
  '/api/chat': typeof ApiChatRoute
  '/api/client-delete': typeof ApiClientDeleteRoute
  '/api/client-notes': typeof ApiClientNotesRoute
  '/api/data': typeof ApiDataRoute
  '/api/export': typeof ApiExportRoute
  '/api/faktury': typeof ApiFakturyRoute
  '/api/fio': typeof ApiFioRoute
  '/api/google': typeof ApiGoogleRoute
  '/api/google-ads': typeof ApiGoogleAdsRoute
  '/api/ingest': typeof ApiIngestRoute
  '/api/jarvis-dokument': typeof ApiJarvisDokumentRoute
  '/api/jarvis-memory': typeof ApiJarvisMemoryRoute
  '/api/kalendar': typeof ApiKalendarRoute
  '/api/lead-web': typeof ApiLeadWebRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/login': typeof ApiLoginRoute
  '/api/logout': typeof ApiLogoutRoute
  '/api/mailer': typeof ApiMailerRoute
  '/api/marketing': typeof ApiMarketingRoute
  '/api/merania': typeof ApiMeraniaRoute
  '/api/meta': typeof ApiMetaRoute
  '/api/meta-media': typeof ApiMetaMediaRoute
  '/api/napady': typeof ApiNapadyRoute
  '/api/override': typeof ApiOverrideRoute
  '/api/pagespeed': typeof ApiPagespeedRoute
  '/api/pdf-import': typeof ApiPdfImportRoute
  '/api/periods': typeof ApiPeriodsRoute
  '/api/plany': typeof ApiPlanyRoute
  '/api/premenuj': typeof ApiPremenujRoute
  '/api/raw-uploads': typeof ApiRawUploadsRoute
  '/api/reset': typeof ApiResetRoute
  '/api/session': typeof ApiSessionRoute
  '/api/sprava': typeof ApiSpravaRoute
  '/api/sso': typeof ApiSsoRoute
  '/api/users': typeof ApiUsersRoute
  '/api/vedomost': typeof ApiVedomostRoute
  '/api/vzas-notes': typeof ApiVzasNotesRoute
  '/api/vzas-settings': typeof ApiVzasSettingsRoute
  '/api/vzas-status': typeof ApiVzasStatusRoute
  '/api/vzas-weeks': typeof ApiVzasWeeksRoute
  '/api/web-obsah': typeof ApiWebObsahRoute
  '/api/wishlist': typeof ApiWishlistRoute
  '/api/zosit': typeof ApiZositRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/algo'
    | '/api/anomaly'
    | '/api/btc-reserve'
    | '/api/chat'
    | '/api/client-delete'
    | '/api/client-notes'
    | '/api/data'
    | '/api/export'
    | '/api/faktury'
    | '/api/fio'
    | '/api/google'
    | '/api/google-ads'
    | '/api/ingest'
    | '/api/jarvis-dokument'
    | '/api/jarvis-memory'
    | '/api/kalendar'
    | '/api/lead-web'
    | '/api/leads'
    | '/api/login'
    | '/api/logout'
    | '/api/mailer'
    | '/api/marketing'
    | '/api/merania'
    | '/api/meta'
    | '/api/meta-media'
    | '/api/napady'
    | '/api/override'
    | '/api/pagespeed'
    | '/api/pdf-import'
    | '/api/periods'
    | '/api/plany'
    | '/api/premenuj'
    | '/api/raw-uploads'
    | '/api/reset'
    | '/api/session'
    | '/api/sprava'
    | '/api/sso'
    | '/api/users'
    | '/api/vedomost'
    | '/api/vzas-notes'
    | '/api/vzas-settings'
    | '/api/vzas-status'
    | '/api/vzas-weeks'
    | '/api/web-obsah'
    | '/api/wishlist'
    | '/api/zosit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/algo'
    | '/api/anomaly'
    | '/api/btc-reserve'
    | '/api/chat'
    | '/api/client-delete'
    | '/api/client-notes'
    | '/api/data'
    | '/api/export'
    | '/api/faktury'
    | '/api/fio'
    | '/api/google'
    | '/api/google-ads'
    | '/api/ingest'
    | '/api/jarvis-dokument'
    | '/api/jarvis-memory'
    | '/api/kalendar'
    | '/api/lead-web'
    | '/api/leads'
    | '/api/login'
    | '/api/logout'
    | '/api/mailer'
    | '/api/marketing'
    | '/api/merania'
    | '/api/meta'
    | '/api/meta-media'
    | '/api/napady'
    | '/api/override'
    | '/api/pagespeed'
    | '/api/pdf-import'
    | '/api/periods'
    | '/api/plany'
    | '/api/premenuj'
    | '/api/raw-uploads'
    | '/api/reset'
    | '/api/session'
    | '/api/sprava'
    | '/api/sso'
    | '/api/users'
    | '/api/vedomost'
    | '/api/vzas-notes'
    | '/api/vzas-settings'
    | '/api/vzas-status'
    | '/api/vzas-weeks'
    | '/api/web-obsah'
    | '/api/wishlist'
    | '/api/zosit'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/api/algo'
    | '/api/anomaly'
    | '/api/btc-reserve'
    | '/api/chat'
    | '/api/client-delete'
    | '/api/client-notes'
    | '/api/data'
    | '/api/export'
    | '/api/faktury'
    | '/api/fio'
    | '/api/google'
    | '/api/google-ads'
    | '/api/ingest'
    | '/api/jarvis-dokument'
    | '/api/jarvis-memory'
    | '/api/kalendar'
    | '/api/lead-web'
    | '/api/leads'
    | '/api/login'
    | '/api/logout'
    | '/api/mailer'
    | '/api/marketing'
    | '/api/merania'
    | '/api/meta'
    | '/api/meta-media'
    | '/api/napady'
    | '/api/override'
    | '/api/pagespeed'
    | '/api/pdf-import'
    | '/api/periods'
    | '/api/plany'
    | '/api/premenuj'
    | '/api/raw-uploads'
    | '/api/reset'
    | '/api/session'
    | '/api/sprava'
    | '/api/sso'
    | '/api/users'
    | '/api/vedomost'
    | '/api/vzas-notes'
    | '/api/vzas-settings'
    | '/api/vzas-status'
    | '/api/vzas-weeks'
    | '/api/web-obsah'
    | '/api/wishlist'
    | '/api/zosit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAlgoRoute: typeof ApiAlgoRoute
  ApiAnomalyRoute: typeof ApiAnomalyRoute
  ApiBtcReserveRoute: typeof ApiBtcReserveRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiClientDeleteRoute: typeof ApiClientDeleteRoute
  ApiClientNotesRoute: typeof ApiClientNotesRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiExportRoute: typeof ApiExportRoute
  ApiFakturyRoute: typeof ApiFakturyRoute
  ApiFioRoute: typeof ApiFioRoute
  ApiGoogleRoute: typeof ApiGoogleRoute
  ApiGoogleAdsRoute: typeof ApiGoogleAdsRoute
  ApiIngestRoute: typeof ApiIngestRoute
  ApiJarvisDokumentRoute: typeof ApiJarvisDokumentRoute
  ApiJarvisMemoryRoute: typeof ApiJarvisMemoryRoute
  ApiKalendarRoute: typeof ApiKalendarRoute
  ApiLeadWebRoute: typeof ApiLeadWebRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiLoginRoute: typeof ApiLoginRoute
  ApiLogoutRoute: typeof ApiLogoutRoute
  ApiMailerRoute: typeof ApiMailerRoute
  ApiMarketingRoute: typeof ApiMarketingRoute
  ApiMeraniaRoute: typeof ApiMeraniaRoute
  ApiMetaRoute: typeof ApiMetaRoute
  ApiMetaMediaRoute: typeof ApiMetaMediaRoute
  ApiNapadyRoute: typeof ApiNapadyRoute
  ApiOverrideRoute: typeof ApiOverrideRoute
  ApiPagespeedRoute: typeof ApiPagespeedRoute
  ApiPdfImportRoute: typeof ApiPdfImportRoute
  ApiPeriodsRoute: typeof ApiPeriodsRoute
  ApiPlanyRoute: typeof ApiPlanyRoute
  ApiPremenujRoute: typeof ApiPremenujRoute
  ApiRawUploadsRoute: typeof ApiRawUploadsRoute
  ApiResetRoute: typeof ApiResetRoute
  ApiSessionRoute: typeof ApiSessionRoute
  ApiSpravaRoute: typeof ApiSpravaRoute
  ApiSsoRoute: typeof ApiSsoRoute
  ApiUsersRoute: typeof ApiUsersRoute
  ApiVedomostRoute: typeof ApiVedomostRoute
  ApiVzasNotesRoute: typeof ApiVzasNotesRoute
  ApiVzasSettingsRoute: typeof ApiVzasSettingsRoute
  ApiVzasStatusRoute: typeof ApiVzasStatusRoute
  ApiVzasWeeksRoute: typeof ApiVzasWeeksRoute
  ApiWebObsahRoute: typeof ApiWebObsahRoute
  ApiWishlistRoute: typeof ApiWishlistRoute
  ApiZositRoute: typeof ApiZositRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zosit': {
      id: '/api/zosit'
      path: '/api/zosit'
      fullPath: '/api/zosit'
      preLoaderRoute: typeof ApiZositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wishlist': {
      id: '/api/wishlist'
      path: '/api/wishlist'
      fullPath: '/api/wishlist'
      preLoaderRoute: typeof ApiWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-obsah': {
      id: '/api/web-obsah'
      path: '/api/web-obsah'
      fullPath: '/api/web-obsah'
      preLoaderRoute: typeof ApiWebObsahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vzas-weeks': {
      id: '/api/vzas-weeks'
      path: '/api/vzas-weeks'
      fullPath: '/api/vzas-weeks'
      preLoaderRoute: typeof ApiVzasWeeksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vzas-status': {
      id: '/api/vzas-status'
      path: '/api/vzas-status'
      fullPath: '/api/vzas-status'
      preLoaderRoute: typeof ApiVzasStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vzas-settings': {
      id: '/api/vzas-settings'
      path: '/api/vzas-settings'
      fullPath: '/api/vzas-settings'
      preLoaderRoute: typeof ApiVzasSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vzas-notes': {
      id: '/api/vzas-notes'
      path: '/api/vzas-notes'
      fullPath: '/api/vzas-notes'
      preLoaderRoute: typeof ApiVzasNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vedomost': {
      id: '/api/vedomost'
      path: '/api/vedomost'
      fullPath: '/api/vedomost'
      preLoaderRoute: typeof ApiVedomostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sso': {
      id: '/api/sso'
      path: '/api/sso'
      fullPath: '/api/sso'
      preLoaderRoute: typeof ApiSsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sprava': {
      id: '/api/sprava'
      path: '/api/sprava'
      fullPath: '/api/sprava'
      preLoaderRoute: typeof ApiSpravaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session': {
      id: '/api/session'
      path: '/api/session'
      fullPath: '/api/session'
      preLoaderRoute: typeof ApiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset': {
      id: '/api/reset'
      path: '/api/reset'
      fullPath: '/api/reset'
      preLoaderRoute: typeof ApiResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/raw-uploads': {
      id: '/api/raw-uploads'
      path: '/api/raw-uploads'
      fullPath: '/api/raw-uploads'
      preLoaderRoute: typeof ApiRawUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/premenuj': {
      id: '/api/premenuj'
      path: '/api/premenuj'
      fullPath: '/api/premenuj'
      preLoaderRoute: typeof ApiPremenujRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/plany': {
      id: '/api/plany'
      path: '/api/plany'
      fullPath: '/api/plany'
      preLoaderRoute: typeof ApiPlanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/periods': {
      id: '/api/periods'
      path: '/api/periods'
      fullPath: '/api/periods'
      preLoaderRoute: typeof ApiPeriodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pdf-import': {
      id: '/api/pdf-import'
      path: '/api/pdf-import'
      fullPath: '/api/pdf-import'
      preLoaderRoute: typeof ApiPdfImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pagespeed': {
      id: '/api/pagespeed'
      path: '/api/pagespeed'
      fullPath: '/api/pagespeed'
      preLoaderRoute: typeof ApiPagespeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/override': {
      id: '/api/override'
      path: '/api/override'
      fullPath: '/api/override'
      preLoaderRoute: typeof ApiOverrideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/napady': {
      id: '/api/napady'
      path: '/api/napady'
      fullPath: '/api/napady'
      preLoaderRoute: typeof ApiNapadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta-media': {
      id: '/api/meta-media'
      path: '/api/meta-media'
      fullPath: '/api/meta-media'
      preLoaderRoute: typeof ApiMetaMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta': {
      id: '/api/meta'
      path: '/api/meta'
      fullPath: '/api/meta'
      preLoaderRoute: typeof ApiMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/merania': {
      id: '/api/merania'
      path: '/api/merania'
      fullPath: '/api/merania'
      preLoaderRoute: typeof ApiMeraniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/marketing': {
      id: '/api/marketing'
      path: '/api/marketing'
      fullPath: '/api/marketing'
      preLoaderRoute: typeof ApiMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/mailer': {
      id: '/api/mailer'
      path: '/api/mailer'
      fullPath: '/api/mailer'
      preLoaderRoute: typeof ApiMailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/logout': {
      id: '/api/logout'
      path: '/api/logout'
      fullPath: '/api/logout'
      preLoaderRoute: typeof ApiLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/login': {
      id: '/api/login'
      path: '/api/login'
      fullPath: '/api/login'
      preLoaderRoute: typeof ApiLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lead-web': {
      id: '/api/lead-web'
      path: '/api/lead-web'
      fullPath: '/api/lead-web'
      preLoaderRoute: typeof ApiLeadWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/kalendar': {
      id: '/api/kalendar'
      path: '/api/kalendar'
      fullPath: '/api/kalendar'
      preLoaderRoute: typeof ApiKalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jarvis-memory': {
      id: '/api/jarvis-memory'
      path: '/api/jarvis-memory'
      fullPath: '/api/jarvis-memory'
      preLoaderRoute: typeof ApiJarvisMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jarvis-dokument': {
      id: '/api/jarvis-dokument'
      path: '/api/jarvis-dokument'
      fullPath: '/api/jarvis-dokument'
      preLoaderRoute: typeof ApiJarvisDokumentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google-ads': {
      id: '/api/google-ads'
      path: '/api/google-ads'
      fullPath: '/api/google-ads'
      preLoaderRoute: typeof ApiGoogleAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google': {
      id: '/api/google'
      path: '/api/google'
      fullPath: '/api/google'
      preLoaderRoute: typeof ApiGoogleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/fio': {
      id: '/api/fio'
      path: '/api/fio'
      fullPath: '/api/fio'
      preLoaderRoute: typeof ApiFioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/faktury': {
      id: '/api/faktury'
      path: '/api/faktury'
      fullPath: '/api/faktury'
      preLoaderRoute: typeof ApiFakturyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/export': {
      id: '/api/export'
      path: '/api/export'
      fullPath: '/api/export'
      preLoaderRoute: typeof ApiExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-notes': {
      id: '/api/client-notes'
      path: '/api/client-notes'
      fullPath: '/api/client-notes'
      preLoaderRoute: typeof ApiClientNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/client-delete': {
      id: '/api/client-delete'
      path: '/api/client-delete'
      fullPath: '/api/client-delete'
      preLoaderRoute: typeof ApiClientDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/btc-reserve': {
      id: '/api/btc-reserve'
      path: '/api/btc-reserve'
      fullPath: '/api/btc-reserve'
      preLoaderRoute: typeof ApiBtcReserveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anomaly': {
      id: '/api/anomaly'
      path: '/api/anomaly'
      fullPath: '/api/anomaly'
      preLoaderRoute: typeof ApiAnomalyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/algo': {
      id: '/api/algo'
      path: '/api/algo'
      fullPath: '/api/algo'
      preLoaderRoute: typeof ApiAlgoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAlgoRoute: ApiAlgoRoute,
  ApiAnomalyRoute: ApiAnomalyRoute,
  ApiBtcReserveRoute: ApiBtcReserveRoute,
  ApiChatRoute: ApiChatRoute,
  ApiClientDeleteRoute: ApiClientDeleteRoute,
  ApiClientNotesRoute: ApiClientNotesRoute,
  ApiDataRoute: ApiDataRoute,
  ApiExportRoute: ApiExportRoute,
  ApiFakturyRoute: ApiFakturyRoute,
  ApiFioRoute: ApiFioRoute,
  ApiGoogleRoute: ApiGoogleRoute,
  ApiGoogleAdsRoute: ApiGoogleAdsRoute,
  ApiIngestRoute: ApiIngestRoute,
  ApiJarvisDokumentRoute: ApiJarvisDokumentRoute,
  ApiJarvisMemoryRoute: ApiJarvisMemoryRoute,
  ApiKalendarRoute: ApiKalendarRoute,
  ApiLeadWebRoute: ApiLeadWebRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiLoginRoute: ApiLoginRoute,
  ApiLogoutRoute: ApiLogoutRoute,
  ApiMailerRoute: ApiMailerRoute,
  ApiMarketingRoute: ApiMarketingRoute,
  ApiMeraniaRoute: ApiMeraniaRoute,
  ApiMetaRoute: ApiMetaRoute,
  ApiMetaMediaRoute: ApiMetaMediaRoute,
  ApiNapadyRoute: ApiNapadyRoute,
  ApiOverrideRoute: ApiOverrideRoute,
  ApiPagespeedRoute: ApiPagespeedRoute,
  ApiPdfImportRoute: ApiPdfImportRoute,
  ApiPeriodsRoute: ApiPeriodsRoute,
  ApiPlanyRoute: ApiPlanyRoute,
  ApiPremenujRoute: ApiPremenujRoute,
  ApiRawUploadsRoute: ApiRawUploadsRoute,
  ApiResetRoute: ApiResetRoute,
  ApiSessionRoute: ApiSessionRoute,
  ApiSpravaRoute: ApiSpravaRoute,
  ApiSsoRoute: ApiSsoRoute,
  ApiUsersRoute: ApiUsersRoute,
  ApiVedomostRoute: ApiVedomostRoute,
  ApiVzasNotesRoute: ApiVzasNotesRoute,
  ApiVzasSettingsRoute: ApiVzasSettingsRoute,
  ApiVzasStatusRoute: ApiVzasStatusRoute,
  ApiVzasWeeksRoute: ApiVzasWeeksRoute,
  ApiWebObsahRoute: ApiWebObsahRoute,
  ApiWishlistRoute: ApiWishlistRoute,
  ApiZositRoute: ApiZositRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
